name: Docs

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
    paths:
      - 'src/**.js'
      - 'src/**.jsx'
      - 'src/**.ts'
      - 'src/**.tsx'
      - 'src/**.json'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nju33'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn
      - run: yarn ci:gen-src-docs
      - run: |
          git remote set-url origin https://nju33:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/nju33/webdriverio-commands.git

          git config --local user.email "nju33.ki@gmail.com"
          git config --local user.name "nju33"

          git fetch
          git checkout master
          git add docs

          if git diff --cached --name-only | grep src > /dev/null; then
            git commit -m "docs: update from Docs workflow"
            git push origin HEAD
          fi
